# Generated by Django 3.0.8 on 2020-07-28 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_diary_diary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='receiver_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diary_receiver_name', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
